name: Scrape Edreams website
on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

  schedule:
    - cron: "*/5 * * * *"
 
jobs:
build:
    runs-on: ubuntu-22.04
    container: node:16
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run scrape
      - run: |
          git config user.name ScrapingBot
          git diff --quiet && git diff --staged --quiet || git commit -am "[bot] update latest flight offers"
          git push origin main