name: Scrape Edreams website
on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook

  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 7.14.2
          run_install: true
      - run: |
          npm install
          node main/index.js
          git config user.name ScrapingBot
          git diff --quiet && git diff --staged --quiet || git commit -am "[bot] update latest flight offers "
          git push origin main